### ISSUE TITLE
图片压缩导致内存溢出

### ISSUE THREAD

**Issue by chenmu5241** [1171736840/spring-file-storage#106]
确认是Thumbnails导致的，每次到这一步都报错！
![image](https://github.com/1171736840/spring-file-storage/assets/24600235/e9b2fd16-7c2b-43b8-8a71-9860740e5476)

**Comment by 1171736840** [comment]
如果你要操作图片，肯定是要把图片都读入内存的，这个没啥好的解决方案，或许你可以让客户端把缩略图也同时上传过来，你使用 thumbnailOf() 方法传入缩略图

**Comment by chenmu5241** [comment]
好的，谢谢了，暂时只能加内存了！
