### ISSUE TITLE
上次多个文件有没有事务问题

### ISSUE THREAD

**Issue by yuzhi-jiang** [1171736840/spring-file-storage#108]
如题，上传多个文件，多次调用fileStorageService.of(file).upload(),有没有事务问题，或者其他上传文件夹/多个文件的方法

**Comment by 1171736840** [comment]
你说的事务问题是指？

**Comment by yuzhi-jiang** [comment]
就是会不会存在 上传3个,上传第3个时中断了(如单机部署minio,或者其他oss),造成垃圾数据

**Comment by 1171736840** [comment]
如果你上传多次，第一次成功了，第二次失败了，此时并不会清理第一个，有需要可以手动清理。
在自动分片上传失败时，会自动清理已上传的分片数据。

**Comment by yuzhi-jiang** [comment]
好的,还有就是自动分片上传,前端的话需要做什么处理吗

**Comment by 1171736840** [comment]
没什么要处理的，正常上传就行，要是文件太大了，前端一次传不完，可以分次上传到服务器后手动合并，然后再上传到对应的存储平台。
后续会做手动分片上传，可能要等一段时间了

**Comment by yuzhi-jiang** [comment]
好的,感谢
