### ISSUE TITLE
请问上传功能里面同时也集成了保存的功能，如果上传成功了，保存这时候失败了，想回滚，有什么方案吗？

### ISSUE THREAD

**Issue by UncleCatWu** [1171736840/spring-file-storage#109]
<img width="840" alt="image" src="https://github.com/1171736840/spring-file-storage/assets/18675524/70adb596-5490-4550-a08b-abad5dec7fd8">

**Comment by 1171736840** [comment]
直接在这个切面里面调用对应存储平台的删除方法就可以了

**Comment by UncleCatWu** [comment]
了解，谢谢大佬😁

**Comment by 1171736840** [comment]
或者是在Recorder中捕获异常，直接调用对应存储平台的删除方法就可以了

**Comment by UncleCatWu** [comment]
好的，还有一个问题想请教，下图中，如果我这样在这个类中同时实现FileRecorder，同时也引用FileStorageService、SpringFileStorageProperties的话，会报循环依赖，不过已经解决了，我是在想这个FileRecorder是不是可以独立出来，想听下大佬的想法
<img width="729" alt="image" src="https://github.com/1171736840/spring-file-storage/assets/18675524/ffaa4b05-81a6-4e6f-879d-cd06a77345d6">

**Comment by UncleCatWu** [comment]
就是不在上传的同时保存，这样也能在FileStorageAutoConfiguration里面也不用去初始化，这个保存功能能完全交给使用者自己去支配

**Comment by 1171736840** [comment]
循环依赖的话这样写
```java
@Lazy
@Autowired
private FileStorageService fileStorageService;
```
独立与否看自己需求，合适最重要

**Comment by UncleCatWu** [comment]
感谢大佬，暂时没什么问题了
