### ISSUE TITLE
建议：项目名可以修改成  xxx-spring-boot-starter 的形式么？可能会更规范一点

### ISSUE THREAD

**Issue by fxbin** [1171736840/spring-file-storage#34]

**Comment by 1171736840** [comment]
目前还不算一个正式版本，等以后会重构项目使其可以脱离Spring运行，以兼容其它平台，使其更合理化，这时候项目名就会是 xxx-spring-boot-starter 的形式了

**Comment by fxbin** [comment]
> 目前还不算一个正式版本，等以后会重构项目使其可以脱离Spring运行，以兼容其它平台，使其更合理化，这时候项目名就会是 xxx-spring-boot-starter 的形式了

这样啊，感谢解答~
