### ISSUE TITLE
怎么对你的方法进行重写啊，我写了子类继承你这个类

### ISSUE THREAD

**Issue by hanchao131415** [1171736840/spring-file-storage#40]
怎么对你的方法进行重写啊，我写了子类继承你这个类

 class S3FileStroage extends AwsS3FileStorage 

  @Override
    public AmazonS3 getClient() {
        if (client == null) {
            AmazonS3ClientBuilder builder = AmazonS3ClientBuilder.standard()
                    .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey)));
            if (StrUtil.isNotBlank(endPoint)) {
                builder.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endPoint, region));
            } else if (StrUtil.isNotBlank(region)) {
                builder.withRegion(region);
            }
            builder.withPathStyleAccessEnabled(true);
            client = builder.build();
        }
        return client;
    }

重写你这个方法加上了   builder.withPathStyleAccessEnabled(true); 但是还是走的你的代码，我这个没有生效，怎么能让我写的子类覆盖父类的方法啊

**Comment by 1171736840** [comment]
需要将子类配置为自定义存储平台，详情点击 [这里](https://spring-file-storage.xuyanwu.cn/#/存储平台?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)

**Comment by hanchao131415** [comment]
感觉没有达到效果，我想重写你的AwsS3FileStorage里面的方法，但是没生效

**Comment by hanchao131415** [comment]
好了
