### ISSUE TITLE
建议：优化一下路径配置方案

### ISSUE THREAD

**Issue by yangkokoi** [1171736840/spring-file-storage#45]
在路径和域名配置的时候可以不加最后的【/】，而是该项目在拼接路径的时候自动加上【/】，为了避免出现两个及以上的斜杆，通过replace进行替换为1个，这样处理有利于防呆设计和满足不同人的编写习惯

**Comment by 1171736840** [comment]
因为这个上传是要存储到数据库中的，同时也会在切面中使用，如果这时候用户配置了两个存储平台，一个带【/】一个不带【/】，这种情况下就会造成使用上的困扰。索性就规定域名后面加【/】，拼接路径时就不会出现这个问题

**Comment by yangkokoi** [comment]
ok
