### ISSUE TITLE
Restricted Identifiers should not be used as Identifiers.

### ISSUE THREAD

**Issue by Suomm** [1171736840/spring-file-storage#46]
说人话就是：cn.xuyanwu.spring.file.storage.recorder.FileRecorder#record 方法名称是JDK 17的关键字，使用报错。

**Comment by 1171736840** [comment]
![image](https://user-images.githubusercontent.com/35297205/212263903-010015bc-5395-4911-9f86-6c76c64925c0.png)
OpenJDK17，正常使用没发现问题

**Comment by Suomm** [comment]
Even if it is technically possible, Restricted Identifiers should not be used as identifiers. This is only possible for compatibility reasons, using it in Java code is confusing and should be avoided.

Note that this applies to any version of Java, including the one where these identifiers are not yet restricted, to avoid future confusion.

是代码规范插件给的一个 Error 错误警告，正常使用没问题。
