### ISSUE TITLE
缩略图背景颜色支持配置么？原图背景颜色为透明，生成的缩略图的背景颜色是黑色

### ISSUE THREAD

**Issue by FaberSober** [1171736840/spring-file-storage#47]
![image](https://user-images.githubusercontent.com/8201946/212537772-23a42f03-f3dd-4e42-b12a-15e05bdd574f.png)

**Comment by 1171736840** [comment]
这是因为缩略图默认保存为jpg，可以尝试改为png，但是png的体积没有jpg小。

因为图片处理使用的是 https://github.com/coobird/thumbnailator 你也可以自己操作缩略图

```java
fileStorageService.of(file)
        .image(img -> img.size(1000,1000))  //将图片大小调整到 1000*1000
        .thumbnail(th -> th.size(200,200))  //再生成一张 200*200 的缩略图（这里操作缩略图）
        .upload();
```
