### ISSUE TITLE
七牛云文件删除问题

### ISSUE THREAD

**Issue by MoliZhaoCn** [1171736840/spring-file-storage#48]
在使用七牛云作为文件云存储时，发生了通过url无法删除的情况，但是调用删除方法时返回的状态为成功，下图可以看出当前默认的platform（指我的系统中的默认文件存储平台）是没有问题的。
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/98500980/212787914-2e271a96-df99-41f1-9128-af609276e05b.png">
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/98500980/212788030-435f08e6-0cb0-4fd1-a75d-c68d418a010d.png">

**Comment by codingEcho** [comment]
遇到了同样的问题

**Comment by 1171736840** [comment]
有没有实现 FileRecorder 这个接口用于保存上传记录？[文档](https://spring-file-storage.xuyanwu.cn/#/基础功能?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)

**Comment by 1171736840** [comment]
> 遇到了同样的问题

有没有实现 FileRecorder 这个接口用于保存上传记录？[文档](https://spring-file-storage.xuyanwu.cn/#/基础功能?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)

**Comment by MoliZhaoCn** [comment]
> 有没有实现 FileRecorder 这个接口用于保存上传记录？[文档](https://spring-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)

没有实现这些方法

**Comment by MoliZhaoCn** [comment]
> > > 有没有实现 FileRecorder 这个接口用于保存上传记录？[文档](https://spring-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)
> > 
> > 
> > 没有实现这些方法
> 
> 根据文档实现这个接口就可以了

我这里出现的问题是，在删除文件后，七牛云存储空间内文件依然存在，实现FileRecorder接口就可以正常删除云上文件了吗？

**Comment by 1171736840** [comment]
> > > > 有没有实现 FileRecorder 这个接口用于保存上传记录？[文档](https://spring-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)
> > > 
> > > 
> > > 没有实现这些方法
> > 
> > 
> > 根据文档实现这个接口就可以了
> 
> 我这里出现的问题是，在删除文件后，七牛云存储空间内文件依然存在，实现FileRecorder接口就可以正常删除云上文件了吗？

是的

**Comment by codingEcho** [comment]
> > 遇到了同样的问题
> 
> 有没有实现 FileRecorder 这个接口用于保存上传记录？[文档](https://spring-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)

实现FileRecorder后，删除正常，感谢！

**Comment by 1171736840** [comment]
把file对象展开看看里面的属性，并且已经实现了
