### ISSUE TITLE
能否将spring的依赖单独放到starter中，核心包中去掉spring的依赖环境

### ISSUE THREAD

**Issue by zhangzhiyong-ay** [1171736840/spring-file-storage#51]

**Comment by 1171736840** [comment]
这个问题很早就考虑到了，在后续的开发计划中会这样做

**Comment by ifzm** [comment]
期待支持 SpringBoot 3.x

**Comment by ifzm** [comment]
👍

**Comment by 1171736840** [comment]
1.0.0版本正式发布

此版本变化较大、更新内容较多，从旧版本升级要做好充分的测试！

- 配置文件中，Amazon S3 存储平台名称由 aws-s3 更改为 amazon-s3
- 配置文件中，GoogleCloud Storage 存储平台名称由 google-cloud 更改为 google-cloud-storage
- 文件记录记录者接口 FileRecorder 的 record 方法更改为 save
- 脱离 SpringBoot 独立运行（方便集成到其它框架中）
- 支持大文件上传（自动分片上传）
- 上传进度监控
- 增加存储平台的 Client 工厂接口，用于支持网络代理、通过 STS 方式初始化存储平台的 Client 对象等功能
- 支持对象存储 Object 级别 ACL （私有桶上传后也可以公开访问）
- 对象存储支持获取临时访问链接（预签名URL）
- 解决上传文件时需要把文件全部读入内存，导致内存占用过大的问题
- 优化 FTP SFTP 的性能问题，使用了 Apache 对象池
- 修复了 WebDav 的兼容性问题，经过测试支持坚果云、NextCloud ，其它平台理论上也支持，可自行测试
- 修复某些 SpringBoot 版本下无法使用本地存储的问题
- 存储平台的 getClient 方法加锁，解决并发情况下重复初始化的问题
- 通过反射调用指定存储平台的方法，使其调用自定义存储平台的独有方法更方便
- 增加了文件适配器接口，可以自行适配各种类型的资源
- 整体架构优化、使其更易于使用


后续更新计划：
1、直接读取 HttpServletRequest 的流进行上传，文件不落盘，速度更快
2、大文件手动分片上传

阅读文档开始使用吧：https://spring-file-storage.xuyanwu.cn/
