### ISSUE TITLE
启动就提示：FileRecorder 的实现类未找到

### ISSUE THREAD

**Issue by xiangyichang** [1171736840/spring-file-storage#54]
cn.xuyanwu.spring.file.storage.FileStorageAutoConfiguration [FileStorageAutoConfiguration.java:352] 没有找到 FileRecorder 的实现类，文件上传之外的部分功能无法正常使用，必须实现该接口才能使用完整功能！

**Comment by 1171736840** [comment]
注意看[文档](https://spring-file-storage.xuyanwu.cn/#/基础功能?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)

**Comment by xiangyichang** [comment]
大意了，谢谢
