### ISSUE TITLE
好像跟undertow不兼容

### ISSUE THREAD

**Issue by xiangyichang** [1171736840/spring-file-storage#55]
按文档配置报错 
cn.xuyanwu.spring.file.storage.exception.FileStorageRuntimeException
Caused by: java.nio.file.FileAlreadyExistsException

**Comment by 1171736840** [comment]
没用过 undertow 不太清除，上次有个人也是报这个错，换了个springboot版本就好了，你可以试试

**Comment by xiangyichang** [comment]
springboot 2.4.6是不兼容的。升级到2.6.0+可以
