### ISSUE TITLE
百度BOS Protocol 可以自定义吗？代码写死的 HTTPS 没法配置

### ISSUE THREAD

**Issue by chenchaoyun0** [1171736840/spring-file-storage#56]
BosClientConfiguration config = new BosClientConfiguration();
config.setCredentials(new DefaultBceCredentials(accessKey,secretKey));
config.setEndpoint(endPoint);
config.setProtocol(Protocol.HTTPS);
client = new BosClient(config);

**Comment by 1171736840** [comment]
你可以复制一份代码，然后[自定义存储平台](https://spring-file-storage.xuyanwu.cn/#/存储平台?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)
