### ISSUE TITLE
大佬 怎么拿出上传文件时的token和dateline凭证 在下载文件时需要带上token和dateline凭证

### ISSUE THREAD

**Issue by ssszy** [1171736840/spring-file-storage#57]

**Comment by ssszy** [comment]
找了好久 debug一圈 找不到获取token和dateline的方法

**Comment by 1171736840** [comment]
哪个存储平台？

**Comment by ssszy** [comment]
七牛云存储平台



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月20日(周一) 上午9:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1171736840/spring-file-storage] 大佬 怎么拿出上传文件时的token和dateline凭证 在下载文件时需要带上token和dateline凭证 (Issue #57)




 
哪个存储平台？

**Comment by 1171736840** [comment]
直接调用下载方法应该就能下载了，其它情况可以参考以下方式
```java
QiniuKodoFileStoragestorage = (QiniuKodoFileStorage) fileStorageService.getFileStorage("qiniu-kodo-1");
QiniuKodoClient client = storage.getClient();
//获取到对应SDK的原生客户端对象，可以进行更多高级操作
```

**Comment by 1171736840** [comment]
要是还不能满足需求，可以复制一份代码，然后[自定义存储平台](https://spring-file-storage.xuyanwu.cn/#/存储平台?id=%e8%8e%b7%e5%8f%96%e5%af%b9%e5%ba%94%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)

**Comment by ssszy** [comment]
好的 谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月20日(周一) 上午9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1171736840/spring-file-storage] 大佬 怎么拿出上传文件时的token和dateline凭证 在下载文件时需要带上token和dateline凭证 (Issue #57)




 
直接调用下载方法应该就能下载了，其它情况可以参考以下方式
 QiniuKodoFileStoragestorage = (QiniuKodoFileStorage) fileStorageService.getFileStorage("qiniu-kodo-1"); QiniuKodoClient client = storage.getClient(); //获取到对应SDK的原生客户端对象，可以进行更多高级操作
