### ISSUE TITLE
minio上传后返回的url无法预览

### ISSUE THREAD

**Issue by yuzhi-jiang** [1171736840/spring-file-storage#59]
minio在上传后返回了
domain/base-path/filename
如 http://[192.168.177.188:9000/test/upload/63f703a21ccab5c9cd06e8bd.txt](http://192.168.177.188:9000/test/upload/63f703a21ccab5c9cd06e8bd.txt)

配置如下：
        end-point: http://192.168.177.188:9000
        bucket-name: test-bucket
        domain: "http://192.168.177.188:9000/" # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: test/ # 基础路径

这是哪里的问题，或者是domain设置不正确，期待回答

它这个是不是应该还有bucket的路径，然后在minio设置bucket为公共的就可以访问，那么如何在私有模式下可以呢

**Comment by 1171736840** [comment]
minio开启公共读了吗？登录minio控制台，看看文件有没有上传成功

**Comment by yuzhi-jiang** [comment]
开启了公共读，但是生成的url也少一个bucket-name，需要手动加上才可以访问

**Comment by 1171736840** [comment]
具体在哪里少，你在domain或base-path中加上就好了

**Comment by yuzhi-jiang** [comment]
ok,在domain加上可用
