### ISSUE TITLE
使用8版本以上的minio可能会有的问题

### ISSUE THREAD

**Issue by qinfengge** [1171736840/spring-file-storage#60]
okhttp3.RequestBody.create([BLokhttp3/MediaType;)Lokhttp3/RequestBody;
解决方法为在pom中
覆盖SpringBoot中okhttp3的旧版本声明，解决MinIO 8.4.x的依赖冲突
        <okhttp3.version>4.10.0</okhttp3.version>

**Comment by 1171736840** [comment]
感谢，我会增加到常见问题中的
