### ISSUE TITLE
minio支持分片上传和断点续传吗

### ISSUE THREAD

**Issue by qinfengge** [1171736840/spring-file-storage#61]
minio支持分片上传和断点续传吗

**Comment by 1171736840** [comment]
暂不支持，后续版本会支持，目前可以[自定义存储平台](https://spring-file-storage.xuyanwu.cn/#/存储平台?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)实现，或者[获取对应平台](https://spring-file-storage.xuyanwu.cn/#/存储平台?id=%e8%8e%b7%e5%8f%96%e5%af%b9%e5%ba%94%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)的 Client 手动操作

**Comment by qinfengge** [comment]
好的，感谢回复
