### ISSUE TITLE
fileStorageService判断文件是否存在走的是DefaultFileRecorder返回null，导致无法走到具体的exists直接返回为false

### ISSUE THREAD

**Issue by yuzhi-jiang** [1171736840/spring-file-storage#63]
如题：
fileStorageService判断文件是否存在走的是DefaultFileRecorder返回null，导致无法走到具体的exists直接返回为false
![image](https://user-images.githubusercontent.com/45190043/222322502-c8be2d95-d1b5-42f4-9a3d-5c4d27eb124e.png)
，看文档，

> 如果还想使用除了保存文件之外的其它功能，例如删除、下载文件，还需要实现 FileRecorder 这个接口，把文件信息保存到数据库中。
 
是要实现该接口吗，不使用数据库保存，可以用该方法（exist）吗

**Comment by 1171736840** [comment]
文档已经说得很清楚了，需要实现这个接口

**Comment by 1171736840** [comment]
你也可以实现一个不保存到数据库的 FileRecorder

**Comment by yuzhi-jiang** [comment]
> 你也可以实现一个不保存到数据库的 FileRecorder

了解，我实现了，不过因为使用的是自定义存储平台，设置了default-platform，报错没有找到对应的平台
![image](https://user-images.githubusercontent.com/45190043/222324200-55bf34ab-b96d-4c70-a997-77f842e9f31a.png)

**Comment by yuzhi-jiang** [comment]
> > 你也可以实现一个不保存到数据库的 FileRecorder
> 
> 了解，我实现了，不过因为使用的是自定义存储平台，设置了default-platform，报错没有找到对应的平台 ![image](https://user-images.githubusercontent.com/45190043/222324200-55bf34ab-b96d-4c70-a997-77f842e9f31a.png)

上传可以，通过setPlatform

**Comment by 1171736840** [comment]
这是因为你自定义的 FileRecorder 中 getByUrl 方法返回的 FileInfo 没有设置 platform 属性

**Comment by yuzhi-jiang** [comment]
好的，解决了，感谢
