### ISSUE TITLE
没法设置上传content-type.

### ISSUE THREAD

**Issue by changyu3590** [1171736840/spring-file-storage#65]
因为有的文件希望上传上去后，给的链接打开是直接下载，或者要求直接渲染到浏览器。

急！！

**Comment by 1171736840** [comment]
如果你用的要是对象存储，请把权限设置为“公共读”，然后照着教程配置好访问域名，上传文件后的url属性就是访问连接，可以直接访问或下载，content-type 在上传时会自动识别，要手动设置就在上传时直接调用 setContentType 方法设置你需要的值就行了
