### ISSUE TITLE
在 springboot 3.0 ， security 6.0  的环境下报错。

### ISSUE THREAD

**Issue by raymondZhong** [1171736840/spring-file-storage#66]
在 springboot 3.0 ， security 6.0  的环境下报错。
![image](https://user-images.githubusercontent.com/1297621/223799210-c7ee8092-50de-4693-822a-11bce1c14d3d.png)

**Comment by 1171736840** [comment]
具体配置呢？

**Comment by raymondZhong** [comment]
![image](https://user-images.githubusercontent.com/1297621/223934073-b448df86-09d5-496c-83a6-8950799cf520.png)

**Comment by 1171736840** [comment]
![image](https://user-images.githubusercontent.com/35297205/223934682-eb2c19fe-1905-493f-9f92-864616205e6e.png)
把这一部分修改一下，应该是 /** 和你使用的某个库冲突了，要是实在不行，就把 enable-access 关了，用Nginx配置

**Comment by 1171736840** [comment]
具体你可以搜索“Spring MVC path-patterns” 具体是用来配置可以通过springboot访问你上传的文件
