### ISSUE TITLE
七牛云平台不可以使用

### ISSUE THREAD

**Issue by xywzxw** [1171736840/spring-file-storage#67]
pom和yml文件中都配置了七牛云的相关信息，上传时提示 没有找到对应的存储平台！
![image](https://user-images.githubusercontent.com/17661568/223905216-5c1a6e7f-d1dd-47cf-8e00-28b4e30ec526.png)

**Comment by 1171736840** [comment]
应该是默认的存储平台没配置，找不到就发配置，我和你说改哪个

**Comment by xywzxw** [comment]
![image](https://user-images.githubusercontent.com/17661568/223905611-c3c1c5a0-e041-48d9-9274-093ade00e75e.png)

**Comment by 1171736840** [comment]
enable-storage 设置为 true

**Comment by xywzxw** [comment]
ok  可以了  为啥其他平台式false就可以

**Comment by xywzxw** [comment]
![image](https://user-images.githubusercontent.com/17661568/223906067-cd9c6e4b-711b-4b66-b9b5-6b8137b98404.png)

**Comment by 1171736840** [comment]
依赖检测和启用开关是分开的，只要配置了就会进行检测依赖
