### ISSUE TITLE
怎么扩展上传存储记录

### ISSUE THREAD

**Issue by arden-yang** [1171736840/spring-file-storage#72]

**Comment by 1171736840** [comment]
你想做什么？请详细描述

**Comment by arden-yang** [comment]
将上传信息保存到数据库

**Comment by arden-yang** [comment]
你这个文件下载只能通过info对象吗，不能通过url,你返回的url只是一个相对路径

**Comment by 1171736840** [comment]
文档中都有，[点击查看](https://spring-file-storage.xuyanwu.cn/#/基础功能?id=%e4%bf%9d%e5%ad%98%e4%b8%8a%e4%bc%a0%e8%ae%b0%e5%bd%95)

**Comment by 1171736840** [comment]
配置文件中吧 domain 参数配置好，url就正确了
