### ISSUE TITLE
Maven 依赖导入不进去

### ISSUE THREAD

**Issue by insight720** [1171736840/spring-file-storage#73]
Maven Repository 也搜索不到依赖。

**Comment by 1171736840** [comment]
尝试更换maven源吧
https://central.sonatype.com/artifact/cn.xuyanwu/spring-file-storage/0.7.0/versions
https://mvnrepository.com/artifact/cn.xuyanwu/spring-file-storage

**Comment by insight720** [comment]
感谢！我用的 Maven 源是阿里的镜像，可能昨天确实有点问题，今天导进去了，但直接搜索是搜不到的，如图：
![QQ截图20230329112621](https://user-images.githubusercontent.com/108797013/228419050-e7755d6f-0b84-4de3-8b6c-3a973a0135f9.png)

**Comment by 1171736840** [comment]
由于权重问题，导致很难搜索到，可以尝试搜索 cn.xuyanwu
