### ISSUE TITLE
  local-plus不能访问相对路径

### ISSUE THREAD

**Issue by yuzhi-jiang** [1171736840/spring-file-storage#74]
local-plus，存储路径设置了相对路径，可以上传（正确），无法访问

**Comment by 1171736840** [comment]
发配置文件

**Comment by yuzhi-jiang** [comment]
![image](https://user-images.githubusercontent.com/45190043/228798363-002df3e5-097f-4feb-88d8-7549c3ff90e1.png)

**Comment by 1171736840** [comment]
不要设置成相对路径，会有很多问题，目前仅在绝对路径下测试通过

**Comment by yuzhi-jiang** [comment]
okok
