### ISSUE TITLE
curl -i -F  "file=@./rc.jpg;filename='rc.jpg'" http://localhost:8080/upload-image 上传后文件名会遗留一个单引号

### ISSUE THREAD

**Issue by peterSZW** [1171736840/spring-file-storage#83]
curl -i -F  "file=@./rc.jpg;filename='rc.jpg'" http://localhost:8080/upload-image 上传后文件名会遗留一个单引号

**Comment by 1171736840** [comment]
这个可以看一下 SpringMVC 的相关文档，文件名都是从 MultipartFile 中获取的，或者简单一点，命令行中去掉单引号
