### ISSUE TITLE
使用minio 上传成功，数据库保存成功，下载失败

### ISSUE THREAD

**Issue by wanx818** [1171736840/spring-file-storage#88]
<img width="1586" alt="image" src="https://github.com/1171736840/spring-file-storage/assets/130518245/47a83ec0-4567-4127-8f3c-cc0a185b2788">
<img width="1549" alt="image" src="https://github.com/1171736840/spring-file-storage/assets/130518245/a554281c-adc9-482a-9b47-94924607b671">

**Comment by 1171736840** [comment]
最近在忙，现在问题解决了吗？

**Comment by wanx818** [comment]
还没有

**Comment by 1171736840** [comment]
上传成功后的url可以用浏览器直接访问吗？

**Comment by wanx818** [comment]
url是可以访问的，昨天做删除文件的操作，也是报错的……

**Comment by 1171736840** [comment]
要不你查查minio中设置的权限是否正常？你给的截图上也看不到错误信息

**Comment by wanx818** [comment]
权限正常，之前是因为实体类中的字段类型导致的报错。解决之后 上传文件正常，删除文件出现  “没有找到对应的存储平台”，请大佬指教 这是什么原因导致的。
<img width="1496" alt="image" src="https://github.com/1171736840/spring-file-storage/assets/130518245/dd17667c-6ae4-4623-8566-652d0e0886f8">
<img width="897" alt="image" src="https://github.com/1171736840/spring-file-storage/assets/130518245/3285a70d-b650-4c10-bf42-6fa56b261d1d">

**Comment by 1171736840** [comment]
检查一下要删除的文件的 platform 是否还存在，应该是使用过程中修改或删除了对应的存储平台

**Comment by wanx818** [comment]
我打了断点，在删除代码执行之前还能看到 storageService 中的存储平台

**Comment by 1171736840** [comment]
对比一下文件的platform值和当前存储平台中的platform是否一致

**Comment by wanx818** [comment]
大佬过目
<img width="1281" alt="image" src="https://github.com/1171736840/spring-file-storage/assets/130518245/877944a7-6f9c-4015-831b-96a6457ad193">

**Comment by 1171736840** [comment]
fileInfo中的platform呢？

**Comment by wanx818** [comment]
嗯，有这方面原因，处理后 删除提示成功，但是minio 中的文件还在

**Comment by 1171736840** [comment]
你debug看一下，删除时拼接的路径和minio上的路径是否一致，可能是哪里有问题导致路径不一致，误以为文件已删除了

**Comment by wanx818** [comment]
好了，多谢🙏
