### ISSUE TITLE
我在使用Minio作为存储平台，但是有多个桶如何配置并使用

### ISSUE THREAD

**Issue by bzw1204** [1171736840/spring-file-storage#90]
我只能通过这种方式去配置不同的桶吗？
![image](https://github.com/1171736840/spring-file-storage/assets/9693637/e8e96fad-d3ba-44f2-96a4-186958225f45)

**Comment by 1171736840** [comment]
也可以根据文档 [动态增减存储平台](https://spring-file-storage.xuyanwu.cn/#/存储平台?id=%e5%8a%a8%e6%80%81%e5%a2%9e%e5%87%8f%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)

**Comment by bzw1204** [comment]
> 也可以根据文档 [动态增减存储平台](https://spring-file-storage.xuyanwu.cn/#/%E5%AD%98%E5%82%A8%E5%B9%B3%E5%8F%B0?id=%e5%8a%a8%e6%80%81%e5%a2%9e%e5%87%8f%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)

后续有没有可能修改成为 bucket-name 支持多输入，这样 密钥域名等等这些配置就只需要配置一份就可以了，上传的时候支持上传指定的桶

**Comment by 1171736840** [comment]
不考虑
